export const GET_EASY_QUESTIONS = 'GET_EASY_QUESTIONS';
export const GET_MEDIUM_QUESTIONS = 'GET_MEDIUM_QUESTIONS';
export const GET_HARD_QUESTIONS = 'GET_HARD_QUESTIONS';

export const ADD_EARNINGS = 'ADD_EARNINGS';